/**
 * Pull Request comment functionality
 * Posts a summary comment with analysis results on GitHub PRs
 */

import * as core from "@actions/core";
import { context, getOctokit } from "@actions/github";
import { ConversionStats } from "./stats";
import { ActionConfig } from "./config";

// Hidden marker to identify our comments for upsert behavior
const COMMENT_MARKER = "<!-- sonarqube-sarif-action -->";

type Octokit = ReturnType<typeof getOctokit>;

/**
 * Format the statistics as a markdown comment
 */
export function formatSummaryMarkdown(
  stats: ConversionStats,
  config: ActionConfig,
): string {
  const { owner, repo } = context.repo;
  const prNumber = config.pullRequestNumber;
  const securityTabUrl = prNumber
    ? `https://github.com/${owner}/${repo}/security/code-scanning?query=pr%3A${prNumber}+tool%3ASonarQube+is%3Aopen`
    : `https://github.com/${owner}/${repo}/security/code-scanning`;
  const sonarQubeUrl = `${config.sonarHostUrl}/dashboard?id=${encodeURIComponent(config.projectKey)}`;

  const severityRows = Object.entries(stats.bySeverity)
    .filter(([_, count]) => count > 0)
    .map(([sev, count]) => `| ${sev} | ${count} |`)
    .join("\n");

  const typeRows = Object.entries(stats.byType)
    .filter(([_, count]) => count > 0)
    .map(([type, count]) => `| ${type} | ${count} |`)
    .join("\n");

  const filteredNote =
    stats.filtered > 0
      ? `\n> ℹ️ ${stats.filtered} issues were filtered out (below ${config.minSeverity} severity threshold)`
      : "";

  const noIssuesMessage =
    stats.totalIssues === 0
      ? "\n\n✅ **No issues found!** Your code looks clean."
      : "";

  return `${COMMENT_MARKER}
## 🔍 SonarQube Analysis Results

| Metric | Value |
|--------|-------|
| Total Issues | ${stats.totalIssues} |
| Unique Rules | ${stats.uniqueRules} |
| Files Affected | ${stats.components} |
${filteredNote}${noIssuesMessage}

${
  severityRows
    ? `### By Severity

| Severity | Count |
|----------|-------|
${severityRows}
`
    : ""
}
${
  typeRows
    ? `### By Type

| Type | Count |
|------|-------|
${typeRows}
`
    : ""
}
🔒 [View in Security Tab](${securityTabUrl}) · 📊 [View in SonarQube](${sonarQubeUrl})

---
<sub>Generated by [SonarQube CE SARIF Action](https://github.com/vmvarela/sonarqube-ce-sarif-action)</sub>
`;
}

/**
 * Find an existing comment from this action
 */
export async function findExistingComment(
  octokit: Octokit,
  owner: string,
  repo: string,
  prNumber: number,
): Promise<number | null> {
  try {
    const { data: comments } = await octokit.rest.issues.listComments({
      owner,
      repo,
      issue_number: prNumber,
      per_page: 100,
    });

    const existingComment = comments.find(
      (comment: (typeof comments)[number]) =>
        comment.body?.includes(COMMENT_MARKER),
    );

    return existingComment?.id ?? null;
  } catch (error) {
    core.debug(`Failed to list comments: ${error}`);
    return null;
  }
}

/**
 * Write a PR comment with analysis results (upsert behavior)
 */
export async function writePrComment(
  config: ActionConfig,
  stats: ConversionStats,
): Promise<void> {
  const token = config.githubToken ?? process.env.GITHUB_TOKEN;

  if (!token) {
    core.warning(
      "GitHub token not available. Skipping PR comment. " +
        "Set pr-comment: false to disable this warning.",
    );
    return;
  }

  const prNumber = config.pullRequestNumber;
  if (!prNumber) {
    core.debug("Not in a pull request context. Skipping PR comment.");
    return;
  }

  const { owner, repo } = context.repo;

  try {
    const octokit = getOctokit(token);
    const body = formatSummaryMarkdown(stats, config);

    // Find existing comment for upsert
    const existingCommentId = await findExistingComment(
      octokit,
      owner,
      repo,
      prNumber,
    );

    if (existingCommentId) {
      // Update existing comment
      await octokit.rest.issues.updateComment({
        owner,
        repo,
        comment_id: existingCommentId,
        body,
      });
      core.info(`Updated existing PR comment (ID: ${existingCommentId})`);
    } else {
      // Create new comment
      const { data: newComment } = await octokit.rest.issues.createComment({
        owner,
        repo,
        issue_number: prNumber,
        body,
      });
      core.info(`Created new PR comment (ID: ${newComment.id})`);
    }
  } catch (error) {
    if (error instanceof Error) {
      core.warning(`Failed to post PR comment: ${error.message}`);
      core.debug(error.stack ?? "No stack trace");
    } else {
      core.warning("Failed to post PR comment: Unknown error");
    }
  }
}
